version: '2'

services:
  monero-explorer:
    # image: xmrto/monero-explorer
    build:
      context: .
      dockerfile: local.Dockerfile
      args:
        BRANCH: v0.16.0.1
        DEBIAN_VERSION: "stable-20200720-slim"
    command: --stagenet
    volumes:
      # /monero in container should eventually contain the contents of the folder .bitmonero/lmdb
      - /mnt/bck/development/Monero/stagenet/lmdb:/monero
      - ./onion-monero-blockchain-explorer/src/templates:/data/templates_template/
    ports:
      - "8081:8081"
    environment:
      - USER_ID=1000
      - PORT=8081
      - LMDB_PATH=/monero
      - ENABLE_AUTOREFRESH=1
      - URL_PREFIX=
      # - URL_PREFIX=/url/path  # nginx location block
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
